language: node_js
node_js:
  - "0.10"

before_install:
  - npm install -g jshint
  - wget https://raw.githubusercontent.com/mozilla/html5-lint/master/html5check.py

script:
  - CHECK=$(for file in *.html; do python ./html5check.py -geh $file; done;)
  - if [[ ! -z "$CHECK" ]]; then echo "$CHECK"; exit 1; fi;
  - jshint --extract auto *.html
  - jshint *.js
